add tests

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,22 +1,46 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-indent() {
-  sed -u 's/^/       /'
-}
+# fail fast
+set -e
 
-echo "-----> Install ffmpeg"
+# parse args
 BUILD_DIR=$1
-VENDOR_DIR="vendor"
-DOWNLOAD_URL="https://megafono.github.io/heroku-buildpack-ffmpeg/static/ffmpeg"
-echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
+CACHE_DIR=$2
 
-cd $BUILD_DIR
-mkdir -p $VENDOR_DIR/ffmpeg/bin
-cd $VENDOR_DIR/ffmpeg/bin
-curl -L $DOWNLOAD_URL -o ffmpeg
+BP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-echo "exporting PATH and LIBRARY_PATH" | indent
-PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
+FFMPEG_DIST="ffmpeg"
+FFMPEG_DIST_TAR="${FFMPEG_DIST}.tar.gz"
+FFMPEG_HOME="${BUILD_DIR}/vendor/ffmpeg"
+
+[ ! -d ${CACHE_DIR} ] && mkdir -p ${CACHE_DIR}
+
+# Download ffmpeg if not in cache
+if [ ! -f ${CACHE_DIR}/${FFMPEG_DIST_TAR} ]; then
+  FFMPEG_URL="https://megafono.github.io/heroku-buildpack-ffmpeg/static/${FFMPEG_DIST_TAR}"
+
+  echo -n "-----> Downloading ${FFMPEG_DIST}....."
+  curl --silent --location ${FFMPEG_URL} > ${CACHE_DIR}/${FFMPEG_DIST_TAR}
+
+  echo " done"
+fi
+
+echo -n "-----> Installing ${FFMPEG_DIST}...."
+
+# Untar ffmpeg
+cd ${BUILD_DIR}
+mkdir -p ${BUILD_DIR}/vendor
+tar -zxf ${CACHE_DIR}/${FFMPEG_DIST_TAR}
+mv target ${FFMPEG_HOME}
+chmod +x ${FFMPEG_HOME}/bin/ffmpeg
+echo " done"
+
+echo -n "-----> Configuring ${FFMPEG_DIST}...."
+
+PROFILE_PATH="$BUILD_DIR/.profile.d/${FFMPEG_DIST}.sh"
 mkdir -p $(dirname $PROFILE_PATH)
-echo 'export PATH="$PATH:$HOME/vendor/ffmpeg/bin"' >> $PROFILE_PATH
-echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/ffmpeg"' >> $PROFILE_PATH
+echo 'export PATH="$PATH:'"${FFMPEG_HOME}/bin"'"' >> $PROFILE_PATH
+echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:'"${FFMPEG_HOME}"'"' >> $PROFILE_PATH
+
+echo " done"
